seperate files for cached ipv4/6, signals instead of fifo, cgnat check

diff --git a/scripts/ddns-start b/scripts/ddns-start
--- a/scripts/ddns-start
+++ b/scripts/ddns-start
@@ -47,29 +47,71 @@ ddns_update_ipv6() {
 ### End of user config
 ###
 
+# Which results to report to the router ipv4|ipv6|both
+REPORT='both'
+# Lock file to prevent multiple instances
 LOCKFILE='/tmp/.ddns-start.lck'
-CACHEFILE='/jffs/configs/.ddns-start.cache'
+# File to store last successfully set ip(s)
+CACHEFILE='/jffs/configs/.ddns-start'
 
+# Check if an IPv4 address is in the LAN range
+#   10.0.0.0 - 10.255.255.255
+#   172.16.0.0 - 172.31.255.255
+#   192.168.0.0 - 192.168.255.255
+# Usage: is_local_ipv4 IPv4
 is_local_ipv4() {
-	printf '%s\n' "$1" | grep -Eq '(^127\.)|(^10\.)|(^172\.1[6-9]\.)|(^172\.2[0-9]\.)|(^172\.3[0-1]\.)|(^192\.168\.)'
+	local a b c d h
+	IFS=. read -r a b c d <<-EOF
+		$1
+	EOF
+	h="$(printf '%0.2x' "$a" "$b" "$c" "$d")"
+
+	if		\
+		{ [ ! "$h" \< '0a000000' ] && [ ! '0affffff' \< "$h" ]; } ||	\
+		{ [ ! "$h" \< 'ac100000' ] && [ ! 'ac1fffff' \< "$h" ]; } ||	\
+		{ [ ! "$h" \< 'c0a80000' ] && [ ! 'c0a8ffff' \< "$h" ]; }
+	then
+		true; return $?
+	fi
+
+	false; return $?
 }
 
+# Check if an IPv4 address is in the CGNAT range
+#   100.64.0.0 - 100.127.255.255
+# Usage: is_nat_ipv4 IPv4
+is_nat_ipv4() {
+	local a b c d h
+	IFS=. read -r a b c d <<-EOF
+		$1
+	EOF
+	h="$(printf '%0.2x' "$a" "$b" "$c" "$d")"
+
+	# shellcheck disable=SC2071
+	[ ! "$h" \< '64400000' ] && [ ! '647fffff' \< "$h" ]; return $?
+}
+
+# Check if an IPv6 address is in the LAN range
+#   ::,::1
+#   fc00::/7
+#   fe80::/10
+# Usage: is_local_ipv6 IPv6
 is_local_ipv6() {
 	printf '%s\n' "$1" | grep -Eq '(^::1?$)|(^[fF][cCdDeE])'
 }
 
-pwait() {
-	local PROCESS_ID
-	for PROCESS_ID in "$@"; do
-		[ -n "$PROCESS_ID" ] && while [ -d "/proc/$PROCESS_ID" ]; do usleep 200000; done
-	done
+# Check if a function is defined
+# Usage: is_function FUNCTION
+is_function() {
+	[ "$(type "$1")" = "$1 is a shell function" ]
 }
+
+# Check for user in main script to allow log messages from subshells
+[ -t 0 ] && { CONSOLE_TTY="$(tty 2>/dev/null)" || unset CONSOLE_TTY; }
 
 # Send message to syslog or terminal if called by a user
 # Usage: ddns_log [PRIORITY] MESSAGE
 # 	Priorities: debug, info, notice, warning, err, crit, alert, emerg
-# Check for user in main script to allow log messages from subshells
-[ -t 0 ] && CONSOLE_TTY="$(tty)"
 ddns_log() {
 	[ $# -lt 2 ] && set -- "" "$@"
 	[ -n "$CONSOLE_TTY" ] && [ "$1" != 'debug' ] && printf '%s\n' "$2" >"$CONSOLE_TTY"
@@ -77,52 +119,30 @@ ddns_log() {
 }
 
 # Make sure only one ddns update runs at a time
+# Usage: ddns_lock
 ddns_lock() {
-	[ ! -p "$LOCKFILE" ] && mknod "$LOCKFILE" p && trap '{ rm -f "$LOCKFILE"; exit; }' EXIT INT TERM
+	[ ! -f "$LOCKFILE" ] && touch "$LOCKFILE" && trap '{ rm -f "$LOCKFILE"; exit; }' EXIT INT TERM
 }
 
 # Read the last updated IPs
+# Usage: ddns_cache_get TYPE
 ddns_cache_get() {
-	if [ -f "$CACHEFILE" ]; then
-		local LINE CACHE_IPV4 CACHE_IPV6
-		while read -r LINE; do
-			case "$LINE" in
-				'IPv4='*) CACHE_IPV4="${LINE#"IPv4="}";;
-				'IPv6='*) CACHE_IPV6="${LINE#"IPv6="}";;
-			esac
-		done < "$CACHEFILE"
-		printf '%s\n' "$CACHE_IPV4 $CACHE_IPV6"
-	fi
+	[ -f "$CACHEFILE.$1" ] && cat "$CACHEFILE.$1"
 }
 
-# Save the current IPs
+# Save the current IP
+# Usage: ddns_cache_set TYPE VALUE
 ddns_cache_set() {
-	local IPV4 IPV6
-	while [ $# -gt 0 ]; do
-		case "$1" in
-			'-4')
-				IPV4="_$2"
-				shift
-			;;
-			'-6')
-				IPV6="_$2"
-				shift
-			;;
-		esac
-		shift
-	done
-	if [ -n "$IPV4" ] && [ -n "$IPV6" ]; then
-		printf 'IPv4=%s\nIPv6=%s\n' "${IPV4#_}" "${IPV6#_}" > "$CACHEFILE"
-	elif [ -n "$IPV4" ]; then
-		sed -ni -e '/^IPv4=/!p' -e "\$aIPv4=${IPV4#_}" "$CACHEFILE"
-	elif [ -n "$IPV6" ]; then
-		sed -ni -e '/^IPv6=/!p' -e "\$aIPv6=${IPV6#_}" "$CACHEFILE"
-	fi
+	printf '%s\n' "$2" > "$CACHEFILE.$1"
 }
 
-# Get IPv4 address
-# Usage: ddns_get_ipv4
+# Get IPv4 address if the passed one is invalid
+# Usage: ddns_get_ipv4 [IPv4]
 ddns_get_ipv4() {
+	if [ -n "$1" ] && ! is_local_ipv4 "$1"; then
+		echo "$1"
+		return
+	fi
 	local IP
 	IP="$(nvram get wan0_ipaddr)"
 	if [ -z "$IP" ] || is_local_ipv4 "$IP"; then
@@ -132,9 +152,13 @@ ddns_get_ipv4() {
 	echo "$IP"
 }
 
-# Get IPv6 address
-# Usage: ddns_get_ipv6
+# Get IPv6 address if the passed one is invalid
+# Usage: ddns_get_ipv6 [IPv6]
 ddns_get_ipv6() {
+	if [ -n "$1" ] && ! is_local_ipv6 "$1"; then
+		echo "$1"
+		return
+	fi
 	local COUNTER=0 IP
 	if [ "$(nvram get ipv6_service)" != 'disabled' ]; then
 		IP="$(nvram get ipv6_rtr_addr)"
@@ -155,68 +179,93 @@ ddns_get_ipv6() {
 ### Start doing stuff
 ###
 
-(
-	# Check this is the only instance
-	if ! ddns_lock; then
-		ddns_log 'ddns update already in progress'
-		return
-	fi
+# Check this is the only instance
+if ! ddns_lock; then
+	ddns_log 'ddns update already in progress'
+	exit
+fi
 
-	# Get the previously set values
-	DDNS_CACHE="$(ddns_cache_get)"
-	CACHE_IPV4="${DDNS_CACHE%% *}"
-	CACHE_IPV6="${DDNS_CACHE##* }"
+# Check if there's anything to do
+if ! is_function 'ddns_update_ipv6' && is_function 'ddns_update_ipv4'; then
+	ddns_log 'info' 'IP updates skipped'
+	/sbin/ddns_custom_updated 1
+	exit
+fi
 
-	# Update both at the same time
-	if [ "$(type ddns_update_ipv6)" = 'ddns_update_ipv6 is a shell function' ]; then
-		(
-			RESULT=1
-			IP="${2:-"$(ddns_get_ipv6)"}"
-			if [ "$CACHE_IPV6" = "$IP" ]; then
-				ddns_log 'IPv6 is up to date'
-			elif ddns_update_ipv6 "$IP"; then
-				ddns_log "IPv6 ddns successfully updated (${IP:-"unset"})"
+# Set sail for fail
+[ "$REPORT" = 'both' ] && trap 'RESULT="fail"' HUP
+
+# Update both IPv4 and IPv6 at the same time
+if is_function 'ddns_update_ipv6' && [ "$(nvram get ipv6_service)" != 'disabled' ]; then
+	(
+		IP="$(ddns_get_ipv6 "$2")"
+		if [ "$(ddns_cache_get ipv6)" = "$IP" ]; then
+			ddns_log 'IPv6 is up to date'
+		elif ddns_update_ipv6 "$IP"; then
+			ddns_log "IPv6 ddns successfully updated (${IP:-"unset"})"
+			ddns_cache_set 'ipv6' "$IP"
+		else
+			ddns_log 'IPv6 failed to update'
+			UPDATE='fail'
+		fi
+
+		if [ "$REPORT" = 'ipv6' ]; then
+			if [ "$UPDATE" = 'fail' ]; then
+				/sbin/ddns_custom_updated 0
 			else
-				ddns_log 'IPv6 failed to update'
-				RESULT=0
+				/sbin/ddns_custom_updated 1
 			fi
-			echo "ipv6 $RESULT $IP" > "$LOCKFILE"
-		) &
-		PID6=$!
-	fi
-	if [ "$(type ddns_update_ipv4)" = 'ddns_update_ipv4 is a shell function' ]; then
-		(
-			RESULT=1
-			IP="${1:-"$(ddns_get_ipv4)"}"
-			if [ -z "$IP" ]; then
-				ddns_log 'Unable to determine IPv4 address'
-				kill "$PID6" 2>/dev/null
-				RESULT=0
-			elif [ "$CACHE_IPV4" = "$IP" ]; then
-				ddns_log 'IPv4 is up to date'
-			elif ddns_update_ipv4 "$IP"; then
-				ddns_log "IPv4 ddns successfully updated ($IP)"
+		elif [ "$REPORT" = 'both' ] && [ "$UPDATE" = 'fail' ]; then
+			kill -HUP "$$"
+		fi
+	) &
+else
+	ddns_log 'info' 'IPv6 update skipped'
+	[ "$REPORT" = 'ipv6' ] && /sbin/ddns_custom_updated 1
+fi
+
+if is_function 'ddns_update_ipv4'; then
+	(
+		IP="$(ddns_get_ipv4 "$1")"
+		if [ -z "$IP" ]; then
+			ddns_log 'Unable to determine IPv4 address'
+			UPDATE='fail'
+		elif is_nat_ipv4 "$IP"; then
+			ddns_log 'IPv4 address using CG-NAT'
+		elif [ "$(ddns_cache_get ipv4)" = "$IP" ]; then
+			ddns_log 'IPv4 is up to date'
+		elif ddns_update_ipv4 "$IP"; then
+			ddns_log "IPv4 ddns successfully updated ($IP)"
+			ddns_cache_set 'ipv4' "$IP"
+		else
+			ddns_log 'IPv4 failed to update'
+			UPDATE='fail'
+		fi
+
+		if [ "$REPORT" = 'ipv4' ]; then
+			if [ "$UPDATE" = 'fail' ]; then
+				/sbin/ddns_custom_updated 0
 			else
-				ddns_log 'IPv4 failed to update'
-				kill "$PID6" 2>/dev/null
-				RESULT=0
+				/sbin/ddns_custom_updated 1
 			fi
-			/sbin/ddns_custom_updated "$RESULT"
-			[ ! -t 0 ] && kill -INT "$$"
-			echo "ipv4 $RESULT $IP" > "$LOCKFILE"
-		) &
-		PID4=$!
+		elif [ "$REPORT" = 'both' ] && [ "$UPDATE" = 'fail' ]; then
+			kill -HUP "$$"
+		fi
+	) &
+else
+	ddns_log 'info' 'IPv4 update skipped'
+	[ "$REPORT" = 'ipv4' ] && /sbin/ddns_custom_updated 1
+fi
+
+# If both are need, wait. Otherwise they'll handle reporting
+if [ "$REPORT" = 'both' ]; then
+	wait
+	if [ "$RESULT" = 'fail' ]; then
+		/sbin/ddns_custom_updated 0
 	else
 		/sbin/ddns_custom_updated 1
 	fi
-
-	# Update cache
-	while [ -d "/proc/$PID4/fd" ] || [ -d "/proc/$PID6/fd" ]; do
-		read -r EVENT RESULT DATA < "$LOCKFILE"
-		case "$EVENT" in
-			'ipv4') [ "$CACHE_IPV4" != "$DATA" ] && [ "$RESULT" = '1' ] && ddns_cache_set -4 "$DATA";;
-			'ipv6') [ "$CACHE_IPV6" != "$DATA" ] && [ "$RESULT" = '1' ] && ddns_cache_set -6 "$DATA";;
-		esac
-	done
-) &
-wait
+elif [ -n "$CONSOLE_TTY" ]; then
+	# leave running for SSH users
+	wait
+fi
